
export const en = {
    Common: {
        submitButton: 'Submit',
        deleteButton: 'Delete',
        cancelButton: 'Cancel',
        noButton: 'No',
        yesButton: 'Yes',
        okButton: 'OK',
    },
    Login: {
        username: 'Username',
        password: 'Password',
        login: 'Login',
        production: 'Production server',
        develop: 'Development server',
    },
    Tabs: {
        work: 'My Work',
        patients: 'Patients',
        chat: 'Chat',
        settings: 'Settings',
    },
    Patients: {
        title: 'My Patients',
        search: 'Search',
        noPatients: 'No data to display',
        maleShort: 'M',
        femaleShort: 'F',
        yo: 'Y/O'
    },
    Patient: {
        title: 'Patient',
        profile: 'Profile',
        carePlans: 'Care Plans',
        tasks: 'Tasks',
        general: 'General',
        flags: 'Flags',
        vital: 'Vital Signs',
        mental: 'Cognitive & Mental',
        body: 'Body Sites',
        quickActions: 'Quick Actions',
        conditions: 'Conditions',
        timeline: 'Timeline',
        created: 'Created {0}',
        executeTask: 'Execute Task',
    },
    Flags: {
        title: 'Flags',
        userTitle: '{0} Flags',
        addFlag: 'Add flag',
        newFlag: 'New Flag',
        editFlag: 'Edit Flag',
        noFlags: 'No data to display',
        deleteFlag: 'You are about to delete a flag. Are you sure?',
        category: 'Category',
        text: 'Text',
        internal: 'Internal',
        startDate: 'Start Date',
        endDate: 'End Date',
        admin: 'Admin',
        behavioral: 'Behavioral',
        clinical: 'Clinical',
        contact: 'Contact',
        drug: 'Drug',
        lab: 'Lab',
        safety: 'Safety',
    },

    Work: {
        title: 'My Work',
        tasks: 'Tasks',
        noData: 'No data to display',
        flags: 'Flags',
        map: 'Map',
        calendar: 'Calendar',
    },

    Tasks: {
        title: 'Tasks',
        noSchedule: 'No Schedule',
        open: 'Open',
        visits: 'Visits',
        closed: 'Closed',
    },

    Task: {
        addTask: 'Add Task',
        taskDetails: 'Task Details',
        task: 'Task',
        patient: 'Patient',
        category: 'Category',
        requester: 'Opened By',
        when: 'When',
        visit: 'Visit',
        status: 'Status: {0}',
        whatToDo: 'What to Do',
        assignTo: 'Assign to',
        notes: 'Notes',
        plan: 'Plan',
        me: 'Me',
        selectPractitioner: 'Select Practitioner',
        all: 'All',
        open: 'Open',
        closed: 'Closed',
        filterTasks: 'Filter Tasks',
        selectActivity: 'Select Activity',
        deleteTask: 'You are about to delete a task. Are you sure?',
    },

    Visit: {
        selectAVisit: 'Select a Visit',
        patient: 'Patient',
        newVisit: 'Schedule a New Visit',
        date: 'Date',
        start: 'Start',
        end: 'End',
        pickStartTime: 'Pick a start time',
        pickEndTime: 'Pick an end time',
        reason: 'Reason',
    },

    Chat: {
        title: 'Chat',
    },

    Settings: {
        title: 'Settings',
        qa: 'QA Mode',
    },

    Priorities: {
        routine: 'Routine',
        urgent: 'Urgent',
        asap: 'ASAP',
        stat: 'STAT',
    },

    Statuses: {
        draft: 'Draft',
        active: 'Active',
        'on-hold': 'On hold',
        revoked: 'Revoked',
        completed: 'Completed',
        'entered-in-error': 'Entered in error',
        unknown: 'Unknown',
    },

    Calendar: {
        myCalendar: 'My Calendar',
        noVisits: 'No visits on {0}',
        noTask: 'No Task',
    },

    Questionnaire :{
        general: 'General',
        basedOnTask: 'Based on Task',
        patient: 'Patient',
        practitioner: 'Practitioner',
        fillDate: 'Fill Date',
        upTo3Images: 'Up to 3 images',
        submit: 'Submit',
        submitText: 'You are about to submit the form',
    }
};
