
export const en = {
    Common: {
        submitButton: 'Submit',
        deleteButton: 'Delete',
        cancelButton: 'Cancel',
        noButton: 'No',
        yesButton: 'Yes',
        okButton: 'OK',
        doneButton: 'Done',
        sendButton: 'Send',
    },
    System: {
        sessionExpired: 'Session has expired. Please login again.',
    },
    Login: {
        appName: 'Hestia',
        homecarePlatform: 'A Homecare Platform',
        username: 'Username',
        password: 'Password',
        login: 'Login',
        production: 'Development Secured',
        develop: 'Development server',
    },
    Tabs: {
        work: 'My Work',
        patients: 'Patients',
        chat: 'Chat',
        settings: 'Settings',
        messages: 'Messages',
    },
    Patients: {
        title: 'My Patients',
        search: 'Search',
        noPatients: 'No data to display',
        maleShort: 'M',
        femaleShort: 'F',
        yo: 'Y/O'
    },
    Patient: {
        title: 'Patient Profile',
        openTasks: 'Open Tasks',
        completedTasks: 'Completed Tasks',
        general: 'General',
        flags: 'Alerts',
        vital: 'Vital Signs',
        conditions: 'Conditions',
        cognitive: 'Cognitive',
    },
    Flags: {
        title: 'Alerts',
        userTitle: '{0} Alerts',
        addFlag: 'Add Alert',
        newFlag: 'New Alert',
        details: 'Alert Details',
        editFlag: 'Edit Alert',
        noFlags: 'No data to display',
        deleteFlag: 'You are about to delete the alert. Are you sure?',
        category: 'Category',
        text: 'Text',
        internal: 'Internal',
        startDate: 'Valid From',
        endDate: 'Valid To',
        to: 'to',
    },

    Flag: {
        menuEdit: 'Edit',
        menuDelete: 'Delete',
        menuCreate: 'Create Alert',
        status: 'Status',
        lastUpdate: 'Last Update',
        patient: 'Patient',
        flag: 'Alert',
        patientName: 'Patient Name',
        category: 'Category',
        validFrom: 'Valid From',
        validTo: 'Valid To',
        editFlag: 'Edit Alert'
    },

    Work: {
        title: 'My Work',
        tasks: 'All Tasks',
        noData: 'No data to display',
        flags: 'All Flags',
        map: 'Map',
        calendar: 'Calendar',
        alerts: 'Alerts',
        filter: 'Filter',
    },

    Tasks: {
        title: 'Tasks',
        noSchedule: 'No Schedule',
        open: 'Open',
        visits: 'Visits',
        closed: 'Closed',
    },

    Task: {
        addTask: 'New Task',
        taskDetails: 'Task Details',
        task: 'Task',
        taskName: 'Task Name',
        editTask: 'Task - Edit',
        taskId: 'Task ID',
        created: 'Created',
        patient: 'Patient',
        selectAPatient: 'Select a patient',
        selectAPatientFirst: 'Please, select a patient first',
        category: 'Category',
        requester: 'Created By',
        performer: 'Assigned To',
        schedule: 'Schedule',
        when: 'When',
        priority: 'Priority',
        visit: 'Visit',
        status: 'Status: {0}',
        whatToDo: 'What to Do',
        assignTo: 'Assign to',
        notes: 'Notes',
        plan: 'Plan',
        me: 'Me',
        selectPractitioner: 'Select Practitioner',
        selectAnActivity: 'Select an activity',
        assignToOther: 'Assign to Other',
        all: 'All',
        open: 'Open',
        closed: 'Closed',
        filterTasks: 'Filter Tasks',
        selectActivity: 'Select Activity',
        deleteTask: 'You are about to delete a task. Are you sure?',
        menuEdit: 'Edit',
        menuCreate: 'Create Task',
        menuExecute: 'Execute',
        menuCancel: 'Cancel Task',
        menuSendMail: 'Send mail',
        sendText: 'You are about to send the following details of the completed task: \n\n' +
            '- Task Name\n' +
            '- All questions and their answers\n' +
            '- All Images\n' +
            '- Patient\'s main details\n' +
            '- Practitioner\'s name and license\n\n' +
            'The email will be sent to',
        sendInfo: 'To change the email address go to Settings',
        mailSent: 'Mail sent',
        noEmailToSend: 'Please go to Settings and set email first',
        executionDetails: 'Task Execution Details',
    },

    Visit: {
        selectAVisit: 'Select a Visit',
        editVisit: 'Edit Visit',
        patient: 'Patient',
        newVisit: 'New Visit',
        date: 'Date',
        start: 'Start',
        end: 'End',
        pickStartTime: 'Pick a start time',
        pickEndTime: 'Pick an end time',
        reason: 'Reason',
        noVisit: 'No Schedule',
        removeSchedule: 'Remove Schedule',
        addToExisting: 'Add to existing visit',
        schedule: 'Schedule',
    },

    Chat: {
        title: 'Chat',
    },

    Settings: {
        title: 'Settings',
        qa: 'QA Mode',
        imageQuality: 'Image Quality',
        original: 'Original',
        medium: 'Medium',
        small: 'Small',
        currentUser: 'Current User',
        authentication: 'Authentication',
        azureAD: 'Azure AD',
        noAuth: 'No Auth',
        upn: 'UPN',
        practitionerId: 'Practitioner ID',
        accessToken: 'Access Token',
        deleteToken: 'Delete',
        logout: 'Logout',
        emailAddress: 'Email',
        servername: 'Servername',
    },

    Priorities: {
        routine: 'Routine',
        urgent: 'Urgent',
        asap: 'ASAP',
        stat: 'STAT',
    },

    Statuses: {
        draft: 'Draft',
        active: 'Active',
        'on-hold': 'On hold',
        revoked: 'Revoked',
        completed: 'Completed',
        'entered-in-error': 'Entered in error',
        unknown: 'Unknown',
    },

    Categories: {
        admin: 'Admin',
        behavioral: 'Behavioral',
        clinical: 'Clinical',
        contact: 'Contact',
        drug: 'Drug',
        lab: 'Lab',
        safety: 'Safety',
    },

    Calendar: {
        myCalendar: 'My Calendar',
        noVisits: 'No visits on {0}',
        noTask: 'No Task',
    },

    Questionnaire: {
        title: 'Execute Task',
        general: 'General',
        basedOnTask: 'Based on Task',
        patient: 'Patient',
        practitioner: 'Practitioner',
        fillDate: 'Fill Date',
        upTo3Images: 'Up to 3 images',
        submit: 'Submit',
        submitText: 'You are about to submit the Task. Are you sure?',
    },

    PatientTasks: {
        title: 'Patient\'s Tasks',
        open: 'Open',
        completed: 'Completed',
        noData: 'No data to display',
        executionDate: 'Execution Date',
        sorting: 'Sort task',
        sortByName: 'By Name',
        sortByDateAsc: 'By Date Ascending',
        sortByDateDesc: 'By Date Descending',
    },

    QuestionnaireResponse: {
        completedTask: 'Completed Task',
        responseNotFound: 'Response has not been found!'
    },

    General: {
        title: 'Patient - General',
        patientId: 'Patient ID',
        age: 'Age',
        gender: 'Gender',
        identifier: 'Identifier',
        firstName: 'First Name',
        lastName: 'Last Name',
        fullName: 'Full Name',
        license: 'License',
        role: 'Role',
        identity: 'Identity',
        address: 'Address',
        relatedPersons: 'Related Persons',
    },
};
